-- Adminer 4.7.1 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `articles_table`;
CREATE TABLE `articles_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `articles_table` (`id`, `title`, `body`) VALUES
(4,	'Put A Cheeseburger In Your Ipsum',	'<p>\r\nEpic cheeseburgers come in all kinds of manifestations, but we want them in and around our mouth no matter what. Slide those smashed patties with the gently caramelized meat fat between a toasted brioche bun and pass it over. You fall in love with the cheeseburger itself but the journey ain’t half bad either.\r\n</p>\r\n\r\n<p>\r\nThey’re the childhood friend that knows your highest highs and lowest lows. They’ve been with you through thick and thin and they’re the best at keeping secrets. Whether it’s dressed up or informal, cheeseburgers have your back.\r\n</p>\r\n\r\n<p>\r\nSometimes we lose sight of what really matters in life. There’s something to be said for a gourmet brie and truffle burger paired with parmesan frites, but don’t let that make you forget about the ol’ faithful with American cheddar and a squishy bun. Lettuce remind you that cheeseburgers come in all forms - bun intended.\r\n</p>\r\n\r\n<p>\r\nPop quiz: what’s the greatest thing to happen to your mind, body, and soul in recent history? A cheeseburger, obviously. Cheeseburgers know that what you want can also be what you need.\r\n</p>'),
(5,	'Put A Cheeseburger In Your Ipsum 2',	'<p>\r\nThere is debate on who painstakingly birthed our favourite monumental flavor creation into existence. What really matters is that, at the end of the day, we can collectively relish in the sweet glory of it all. From beef-to-bun ratio, ‘how much is too much?’ cheese, and the careful alchemy of condiments, every cheeseburger is a small mountain of heaven.\r\n</p>\r\n\r\n<p>\r\nAny day without a cheeseburger in it is a waste. You can find a cheeseburger no matter where you go in the world, so you have no excuse to miss out on the glory that some people can only dream of. Step up to the plate.\r\n</p>'),
(6,	'cupcakeipsum.com',	'<p>\r\nApple pie gummi bears gummi bears. Cheesecake cake cake tiramisu liquorice carrot cake. Tart candy danish jelly-o danish candy chocolate cake. Caramels cake toffee gummies ice cream bonbon apple pie candy oat cake.\r\n</p>\r\n<p>\r\nCake candy lemon drops halvah sweet roll cheesecake brownie toffee. Topping apple pie jelly \r\nliquorice cake gummi bears tiramisu jelly. Apple pie gummi bears chupa chups donut halvah.\r\n</p>\r\n<p>\r\nSoufflé chocolate cake cupcake marshmallow. Pastry cookie tart. Lemon drops jelly beans brownie biscuit macaroon cupcake.\r\n</p>\r\n<p>\r\nDanish candy bonbon biscuit sugar plum pastry croissant sugar plum lemon drops. Chupa chups apple pie jelly cake caramels bonbon soufflé jelly-o pudding. Chocolate cake gingerbread brownie. Gingerbread dessert jujubes donut lemon drops candy.\r\n</p>\r\n<p>\r\nCookie carrot cake jelly tart chocolate jelly beans. Dragée jelly-o tootsie roll biscuit marzipan sesame snaps liquorice danish marshmallow. Bonbon lollipop biscuit danish caramels. Jujubes lemon drops chupa chups sweet roll carrot cake topping cupcake dragée.\r\n</p>'),
(7,	'Cougar russian blue',	'<p>\r\nDonskoy lion siberian maine coon birman but donskoy. Tomcat. Manx ocelot. American shorthair. Norwegian forest siamese, bombay but british shorthair but leopard but cheetah and british shorthair. Burmese cornish rex and thai so siamese for ragdoll but ocelot. Siberian ocicat manx for malkin. Kitty malkin, maine coon american shorthair. Bengal lynx and puma. American bobtail scottish fold. Siberian grimalkin. Cougar turkish angora for norwegian forest and cheetah for burmese for havana brown. Cheetah siamese turkish angora. Donskoy himalayan so cheetah. Tiger ocicat or tiger burmese siberian cornish rex. Grimalkin bobcat, donskoy lion so kitten tiger bobcat. Cornish rex bengal or panther, ocelot and cougar lynx. Bengal himalayan cougar, british shorthair bobcat. Himalayan. Lynx russian blue or cougar russian blue so kitty. Thai panther and jaguar puma kitty kitty bobcat. American shorthair thai, munchkin yet cougar munchkin tom so persian. Abyssinian . Thai maine coon manx sphynx, kitten but bobcat siberian.\r\n</p>\r\n<p>\r\nNorwegian forest american shorthair and thai, manx leopard devonshire rex. Jaguar maine coon british shorthair turkish angora devonshire rex, grimalkin but leopard. Munchkin. Lynx donskoy or burmese bobcat turkish angora cheetah sphynx. Siberian singapura british shorthair tabby. Maine coon malkin ragdoll. Tomcat kitty for bombay for british shorthair. Donskoy munchkin so malkin yet lion ragdoll and egyptian mau and munchkin. Tom balinese maine coon but siamese american bobtail. Ragdoll mouser for burmese tabby lynx. Havana brown ocicat or bengal. Himalayan ragdoll birman or lynx british shorthair american shorthair or turkish angora. Malkin birman so kitty so manx for cornish rex for devonshire rex. Devonshire rex. Tabby kitty himalayan yet munchkin donskoy. Turkish angora. Mouser. Puma mouser and himalayan, so british shorthair burmese but bombay or cornish rex. Ragdoll sphynx thai but ocelot. Singapura bengal grimalkin tomcat panther yet scottish fold, for kitten. Egyptian mau himalayan ocelot egyptian mau. Cougar bobcat. Savannah singapura kitty for ocelot, yet russian blue cheetah. Manx tiger birman bobcat ragdoll. Ocelot.\r\n</p>\r\n<p>\r\nSavannah kitty donskoy but tabby leopard kitten. Lion kitty bengal, but cornish rex. Bombay puma. Persian ragdoll kitty tabby, or bombay. Siberian norwegian forest and siberian for bombay for ocicat yet lion, for tiger. Donskoy. Tabby malkin, siamese. Thai munchkin british shorthair yet mouser. Bombay cornish rex. Havana brown birman ragdoll ocelot and puma or havana brown, but devonshire rex. \r\n</p>'),
(8,	'Zombies & Brains',	'<p>\r\nZombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.\r\n</p>');

-- 2019-09-20 12:56:27
